// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Newbie.Repositories.Models
{
    [Table("article")]
    public partial class Article
    {
        [Key]
        [Column("article_id", TypeName = "int(11)")]
        public int ArticleId { get; set; }
        [Required]
        [Column("title")]
        [StringLength(50)]
        public string Title { get; set; }
        [Column("content")]
        [StringLength(4000)]
        public string Content { get; set; }
        [Column("author")]
        [StringLength(50)]
        public string Author { get; set; }
    }
}