// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Newbie.Repositories.Models
{
    [Table("members_public")]
    [Index(nameof(MemberId), Name = "member_id")]
    public partial class MembersPublic
    {
        [Required]
        [Column("member_id")]
        [StringLength(50)]
        public string MemberId { get; set; }
        [Required]
        [Column("accountname")]
        [StringLength(50)]
        public string Accountname { get; set; }
        [Required]
        [Column("firstname")]
        [StringLength(20)]
        public string Firstname { get; set; }
        [Required]
        [Column("lastname")]
        [StringLength(20)]
        public string Lastname { get; set; }
        [Column("nickname")]
        [StringLength(20)]
        public string Nickname { get; set; }
        [Column("intro")]
        [StringLength(200)]
        public string Intro { get; set; }
        [Column("joindate", TypeName = "date")]
        public DateTime Joindate { get; set; }
        [Key]
        [Column("memberspublic_id", TypeName = "int(11)")]
        public int MemberspublicId { get; set; }
    }
}