// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Newbie.Repositories.Models
{
    [Table("role_article")]
    [Index(nameof(AuthorizationId), Name = "authorization_id")]
    public partial class RoleArticle
    {
        [Key]
        [Column("rolearticle_id", TypeName = "int(11)")]
        public int RolearticleId { get; set; }
        [Column("authorization_id", TypeName = "int(11)")]
        public int AuthorizationId { get; set; }
        [Column("article_id", TypeName = "int(11)")]
        public int ArticleId { get; set; }

        [ForeignKey(nameof(AuthorizationId))]
        [InverseProperty("RoleArticles")]
        public virtual Authorization Authorization { get; set; }
    }
}