// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Newbie.Repositories.Models
{
    [Table("roles")]
    [Index(nameof(AuthorizationId), Name = "authorization_id")]
    [Index(nameof(MemberId), Name = "member_id")]
    public partial class Role
    {
        [Key]
        [Column("role_id", TypeName = "int(11)")]
        public int RoleId { get; set; }
        [Required]
        [Column("member_id")]
        [StringLength(50)]
        public string MemberId { get; set; }
        [Column("authorization_id", TypeName = "int(11)")]
        public int AuthorizationId { get; set; }
    }
}